###
#
# Build the demo app and all dependencies
#
# This workflow does not have secrets access
# when run from a fork. Artifacts are uploaded
# and used in a subsequent workflow with more
# privileges which does not run unsafe commands.
#
# https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
#
###

name: Build Demo App
on:
  pull_request:
    paths:
      - 'packages/components-angular/**'
      - 'packages/demo/**'
      - 'packages/styles/src/**'
      - 'packages/styles/*'
      - '!packages/styles/jest.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ../actions/setup-pnpm.yml

      - name: Bootstrap & Build Design System
        run: |
          pnpm --filter design-system-demo... install
          pnpm --filter design-system-demo... build

      - name: Upload build artifacts
        uses: ../actions/artifact-upload.yml
        with:
          name: design-system-demo
          folder: packages/demo/dist/demo
