###
#
# runs all tests in packages changed since main
#
###

name: Lint files
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: ../actions/setup-pnpm.yml

      - name: Install dependencies of changed packages
        run: pnpm install

      # Test all changed packages and their dependents
      # https://pnpm.io/filtering#--filter-since
      - name: Lint packages
        run: pnpm --filter "...[origin/main]" lint
